# Runs everyday at 10 am
:scheduler:
  :schedule:
    publishing_deals:
      cron: '0 0 10 * * *'
      class: PublishingDeals
    coupon_notifier_job:
      cron: '0 * * * * *'
      class: CouponNotifierJob
